CREATE OR REPLACE VIEW GL_ACCT_DESC_TEMP# AS
select SEGMENT_NAME SEGMENT_NAME, DISPLAY_FLAG DISPLAY_FLAG, ID_FLEX_NUM ID_FLEX_NUM, APPLICATION_COL_NAME APPLICATION_COL_NAME, FLEX_VALUE_SET_ID FLEX_VALUE_SET_ID, SEG_SEQUENCE_NUM SEG_SEQUENCE_NUM, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_ACCT_DESC_TEMP";


