CREATE OR REPLACE VIEW GL_ALLOC_FORMULAS# AS
select ALLOCATION_FORMULA_ID ALLOCATION_FORMULA_ID, ALLOCATION_BATCH_ID ALLOCATION_BATCH_ID, NAME NAME, RUN_SEQUENCE RUN_SEQUENCE, JE_CATEGORY_NAME JE_CATEGORY_NAME, FULL_ALLOCATION_FLAG FULL_ALLOCATION_FLAG, VALIDATION_STATUS VALIDATION_STATUS, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, DESCRIPTION DESCRIPTION, CONVERSION_METHOD_CODE CONVERSION_METHOD_CODE, CURRENCY_CONVERSION_TYPE CURRENCY_CONVERSION_TYPE from "GL"."GL_ALLOC_FORMULAS";


