CREATE OR REPLACE VIEW GL_ARCHIVE_HISTORY# AS
select LEDGER_ID LEDGER_ID, FISCAL_YEAR FISCAL_YEAR, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, DATA_TYPE DATA_TYPE, BUDGET_VERSION_ID BUDGET_VERSION_ID, STATUS STATUS, ARCHIVE_DATE ARCHIVE_DATE, ARCHIVED_BY ARCHIVED_BY, TOTAL_RECORDS_ARCHIVED TOTAL_RECORDS_ARCHIVED, PURGE_DATE PURGE_DATE, PURGED_BY PURGED_BY, TOTAL_RECORDS_PURGED TOTAL_RECORDS_PURGED, LAST_ARCHIVED_EFF_PERIOD_NUM LAST_ARCHIVED_EFF_PERIOD_NUM, LAST_PURGED_EFF_PERIOD_NUM LAST_PURGED_EFF_PERIOD_NUM, ACTUAL_FLAG ACTUAL_FLAG, TOTAL_HEADERS_PURGED TOTAL_HEADERS_PURGED, TOTAL_LINES_PURGED TOTAL_LINES_PURGED, TOTAL_REFERENCES_PURGED TOTAL_REFERENCES_PURGED, MAX_JE_HEADER_ID MAX_JE_HEADER_ID from "GL"."GL_ARCHIVE_HISTORY";


