CREATE OR REPLACE VIEW GL_ARCHIVE_SEGMENT_VALS# AS
select JE_HEADER_ID JE_HEADER_ID, SEGMENT_TYPE_CODE SEGMENT_TYPE_CODE, SEGMENT_VALUE SEGMENT_VALUE, CREATED_BY CREATED_BY, CREATION_DATE CREATION_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_ARCHIVE_SEGMENT_VALS";


