CREATE OR REPLACE VIEW GL_ACCESS_SET_ASSIGNMENTS# AS
select ACCESS_SET_ID ACCESS_SET_ID, LEDGER_ID LEDGER_ID, SEGMENT_VALUE SEGMENT_VALUE, ACCESS_PRIVILEGE_CODE ACCESS_PRIVILEGE_CODE, PARENT_RECORD_ID PARENT_RECORD_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, START_DATE START_DATE, END_DATE END_DATE from "GL"."GL_ACCESS_SET_ASSIGNMENTS";


