CREATE OR REPLACE VIEW GL_AUTO_ALLOC_BATCH_HISTORY# AS
select REQUEST_ID REQUEST_ID, BATCH_ID BATCH_ID, BATCH_TYPE_CODE BATCH_TYPE_CODE, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, STEP_NUMBER STEP_NUMBER, OWNER OWNER, ALLOCATION_METHOD_CODE ALLOCATION_METHOD_CODE, GENERATED_JE_BATCH_ID GENERATED_JE_BATCH_ID, PA_ALLOCATION_RUN_ID PA_ALLOCATION_RUN_ID, STATUS_CODE STATUS_CODE, COMPLETE_FLAG COMPLETE_FLAG, ALL_HEADERS_REVERSED ALL_HEADERS_REVERSED from "GL"."GL_AUTO_ALLOC_BATCH_HISTORY";


