CREATE OR REPLACE VIEW GL_AUTO_ALLOC_BATCHES# AS
select ALLOCATION_SET_ID ALLOCATION_SET_ID, BATCH_ID BATCH_ID, BATCH_TYPE_CODE BATCH_TYPE_CODE, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, STEP_NUMBER STEP_NUMBER, OWNER OWNER, ALLOCATION_METHOD_CODE ALLOCATION_METHOD_CODE, ATTRIBUTE1 ATTRIBUTE1, ATTRIBUTE2 ATTRIBUTE2, ATTRIBUTE3 ATTRIBUTE3, ATTRIBUTE4 ATTRIBUTE4, ATTRIBUTE5 ATTRIBUTE5, ATTRIBUTE6 ATTRIBUTE6, ATTRIBUTE7 ATTRIBUTE7, ATTRIBUTE8 ATTRIBUTE8, ATTRIBUTE9 ATTRIBUTE9, ATTRIBUTE10 ATTRIBUTE10, ATTRIBUTE11 ATTRIBUTE11, ATTRIBUTE12 ATTRIBUTE12, ATTRIBUTE13 ATTRIBUTE13, ATTRIBUTE14 ATTRIBUTE14, ATTRIBUTE15 ATTRIBUTE15, CONTEXT CONTEXT from "GL"."GL_AUTO_ALLOC_BATCHES";


