CREATE OR REPLACE VIEW GL_APPLICATION_GROUPS# AS
select APPLICATION_ID APPLICATION_ID, GROUP_NAME GROUP_NAME, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE from "GL"."GL_APPLICATION_GROUPS";


