CREATE OR REPLACE VIEW GL_BUDGET_BATCHES# AS
select BUDGET_VERSION_ID BUDGET_VERSION_ID, RECURRING_BATCH_ID RECURRING_BATCH_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, STATUS STATUS, LAST_EXECUTED_DATE LAST_EXECUTED_DATE, LAST_EXECUTED_START_PERIOD LAST_EXECUTED_START_PERIOD, LAST_EXECUTED_END_PERIOD LAST_EXECUTED_END_PERIOD from "GL"."GL_BUDGET_BATCHES";


