CREATE OR REPLACE VIEW GL_BUDORG_BC_OPTIONS# AS
select RANGE_ID RANGE_ID, FUNDING_BUDGET_VERSION_ID FUNDING_BUDGET_VERSION_ID, FUNDS_CHECK_LEVEL_CODE FUNDS_CHECK_LEVEL_CODE, AMOUNT_TYPE AMOUNT_TYPE, BOUNDARY_CODE BOUNDARY_CODE, CREATED_BY CREATED_BY, CREATION_DATE CREATION_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, LAST_UPDATE_DATE LAST_UPDATE_DATE from "GL"."GL_BUDORG_BC_OPTIONS";


