CREATE OR REPLACE VIEW GL_BUDGET_VERSIONS# AS
select BUDGET_VERSION_ID BUDGET_VERSION_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, BUDGET_TYPE BUDGET_TYPE, BUDGET_NAME BUDGET_NAME, VERSION_NUM VERSION_NUM, STATUS STATUS, DATE_OPENED DATE_OPENED, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, DESCRIPTION DESCRIPTION, DATE_ACTIVE DATE_ACTIVE, DATE_ARCHIVED DATE_ARCHIVED, ATTRIBUTE1 ATTRIBUTE1, ATTRIBUTE2 ATTRIBUTE2, ATTRIBUTE3 ATTRIBUTE3, ATTRIBUTE4 ATTRIBUTE4, ATTRIBUTE5 ATTRIBUTE5, ATTRIBUTE6 ATTRIBUTE6, ATTRIBUTE7 ATTRIBUTE7, ATTRIBUTE8 ATTRIBUTE8, CONTEXT CONTEXT, CONTROL_BUDGET_VERSION_ID CONTROL_BUDGET_VERSION_ID, IGI_BUD_NYC_FLAG IGI_BUD_NYC_FLAG from "GL"."GL_BUDGET_VERSIONS";


