CREATE OR REPLACE VIEW GL_BC_EVENT_TIMESTAMPS# AS
select CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID, EVENT_CODE EVENT_CODE, DATE_TIMESTAMP DATE_TIMESTAMP, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_BC_EVENT_TIMESTAMPS";


