CREATE OR REPLACE VIEW GL_BUDGET_PERIOD_RANGES# AS
select BUDGET_VERSION_ID BUDGET_VERSION_ID, PERIOD_YEAR PERIOD_YEAR, START_PERIOD_NAME START_PERIOD_NAME, START_PERIOD_NUM START_PERIOD_NUM, END_PERIOD_NAME END_PERIOD_NAME, END_PERIOD_NUM END_PERIOD_NUM, OPEN_FLAG OPEN_FLAG, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY from "GL"."GL_BUDGET_PERIOD_RANGES";


