CREATE OR REPLACE VIEW GL_CONS_FLEX_HIERARCHIES# AS
select SEGMENT_MAP_ID SEGMENT_MAP_ID, PARENT_FLEX_VALUE PARENT_FLEX_VALUE, CHILD_FLEX_VALUE_LOW CHILD_FLEX_VALUE_LOW, CHILD_FLEX_VALUE_HIGH CHILD_FLEX_VALUE_HIGH, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, ATTRIBUTE1 ATTRIBUTE1, ATTRIBUTE2 ATTRIBUTE2, ATTRIBUTE3 ATTRIBUTE3, ATTRIBUTE4 ATTRIBUTE4, ATTRIBUTE5 ATTRIBUTE5, CONTEXT CONTEXT from "GL"."GL_CONS_FLEX_HIERARCHIES";


