CREATE OR REPLACE VIEW GL_CROSS_RATE_RULES# AS
select CONVERSION_TYPE CONVERSION_TYPE, PIVOT_CURRENCY PIVOT_CURRENCY, DESCRIPTION DESCRIPTION, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_CROSS_RATE_RULES";


