CREATE OR REPLACE VIEW GL_COA_MAPPINGS# AS
select COA_MAPPING_ID COA_MAPPING_ID, TO_COA_ID TO_COA_ID, FROM_COA_ID FROM_COA_ID, NAME NAME, SECURITY_FLAG SECURITY_FLAG, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, DESCRIPTION DESCRIPTION, START_DATE_ACTIVE START_DATE_ACTIVE, END_DATE_ACTIVE END_DATE_ACTIVE from "GL"."GL_COA_MAPPINGS";


