CREATE OR REPLACE VIEW GL_CONCURRENCY_CONTROL# AS
select CONCURRENCY_CLASS CONCURRENCY_CLASS, CONCURRENCY_ENTITY_NAME CONCURRENCY_ENTITY_NAME, CONCURRENCY_ENTITY_ID CONCURRENCY_ENTITY_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_CONCURRENCY_CONTROL";


