CREATE OR REPLACE VIEW GL_CROSS_RATE_RULE_DTLS# AS
select CONVERSION_TYPE CONVERSION_TYPE, FROM_CURRENCY FROM_CURRENCY, TO_CURRENCY TO_CURRENCY, ENABLED_FLAG ENABLED_FLAG, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_CROSS_RATE_RULE_DTLS";


