CREATE OR REPLACE VIEW GL_CONS_SEGMENT_MAP# AS
select SEGMENT_MAP_ID SEGMENT_MAP_ID, CONSOLIDATION_ID_11I CONSOLIDATION_ID_11I, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, TO_VALUE_SET_ID TO_VALUE_SET_ID, TO_APPLICATION_COLUMN_NAME TO_APPLICATION_COLUMN_NAME, SEGMENT_MAP_TYPE SEGMENT_MAP_TYPE, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, FROM_VALUE_SET_ID FROM_VALUE_SET_ID, FROM_APPLICATION_COLUMN_NAME FROM_APPLICATION_COLUMN_NAME, SINGLE_VALUE SINGLE_VALUE, ATTRIBUTE1 ATTRIBUTE1, ATTRIBUTE2 ATTRIBUTE2, ATTRIBUTE3 ATTRIBUTE3, ATTRIBUTE4 ATTRIBUTE4, ATTRIBUTE5 ATTRIBUTE5, CONTEXT CONTEXT, PARENT_ROLLUP_VALUE PARENT_ROLLUP_VALUE, COA_MAPPING_ID COA_MAPPING_ID from "GL"."GL_CONS_SEGMENT_MAP";


