CREATE OR REPLACE VIEW GL_CONS_BATCHES# AS
select CONSOLIDATION_ID CONSOLIDATION_ID, CONSOLIDATION_RUN_ID CONSOLIDATION_RUN_ID, JE_BATCH_ID JE_BATCH_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_CONS_BATCHES";


