CREATE OR REPLACE VIEW GL_DOC_SEQUENCE_AUDIT# AS
select DOC_SEQUENCE_ID DOC_SEQUENCE_ID, DOC_SEQUENCE_ASSIGNMENT_ID DOC_SEQUENCE_ASSIGNMENT_ID, DOC_SEQUENCE_VALUE DOC_SEQUENCE_VALUE, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY from "GL"."GL_DOC_SEQUENCE_AUDIT";


