CREATE OR REPLACE VIEW GL_DATE_PERIOD_MAP# AS
select PERIOD_SET_NAME PERIOD_SET_NAME, ACCOUNTING_DATE ACCOUNTING_DATE, PERIOD_NAME PERIOD_NAME, PERIOD_TYPE PERIOD_TYPE, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_DATE_PERIOD_MAP";


