CREATE OR REPLACE VIEW GL_DAILY_CONVERSION_RATES_R10# AS
select SET_OF_BOOKS_ID SET_OF_BOOKS_ID, FROM_CURRENCY_CODE FROM_CURRENCY_CODE, CONVERSION_DATE CONVERSION_DATE, CONVERSION_RATE CONVERSION_RATE, CONVERSION_TYPE CONVERSION_TYPE, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, ATTRIBUTE1 ATTRIBUTE1, ATTRIBUTE2 ATTRIBUTE2, ATTRIBUTE3 ATTRIBUTE3, ATTRIBUTE4 ATTRIBUTE4, ATTRIBUTE5 ATTRIBUTE5, CONTEXT CONTEXT, STATUS_CODE STATUS_CODE, TO_CURRENCY_CODE TO_CURRENCY_CODE from "GL"."GL_DAILY_CONVERSION_RATES_R10";


