CREATE OR REPLACE VIEW GL_ENTITY_BUDGETS# AS
select BUDGET_ENTITY_ID BUDGET_ENTITY_ID, BUDGET_VERSION_ID BUDGET_VERSION_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, FROZEN_FLAG FROZEN_FLAG, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, ATTRIBUTE1 ATTRIBUTE1, ATTRIBUTE2 ATTRIBUTE2, ATTRIBUTE3 ATTRIBUTE3, ATTRIBUTE4 ATTRIBUTE4, ATTRIBUTE5 ATTRIBUTE5, CONTEXT CONTEXT from "GL"."GL_ENTITY_BUDGETS";


