CREATE OR REPLACE VIEW GL_EFC_CHANGED_TRX# AS
select NCU_SET_OF_BOOKS_ID NCU_SET_OF_BOOKS_ID, EURO_SET_OF_BOOKS_ID EURO_SET_OF_BOOKS_ID, APPLICATION_ID APPLICATION_ID, TABLE_NAME TABLE_NAME, PK_ID PK_ID, PK_ID2 PK_ID2, PK_ID3 PK_ID3, ACTION_CODE ACTION_CODE, REFERENCE1 REFERENCE1, REFERENCE2 REFERENCE2, REFERENCE3 REFERENCE3, REFERENCE4 REFERENCE4, REFERENCE5 REFERENCE5 from "GL"."GL_EFC_CHANGED_TRX";


