CREATE OR REPLACE VIEW GL_ENCUMBRANCE_TYPES# AS
select ENCUMBRANCE_TYPE_ID ENCUMBRANCE_TYPE_ID, ENCUMBRANCE_TYPE ENCUMBRANCE_TYPE, ENABLED_FLAG ENABLED_FLAG, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, DESCRIPTION DESCRIPTION, ENCUMBRANCE_TYPE_KEY ENCUMBRANCE_TYPE_KEY, ZD_EDITION_NAME ZD_EDITION_NAME from "GL"."GL_ENCUMBRANCE_TYPES";


