CREATE OR REPLACE VIEW GL_EXTRACT_HISTORY# AS
select LEDGER_ID LEDGER_ID, EXTRACT_PROGRAM_CODE EXTRACT_PROGRAM_CODE, PERIOD_NAME PERIOD_NAME, ACTUAL_FLAG ACTUAL_FLAG, EXTRACT_LEVEL_CODE EXTRACT_LEVEL_CODE, BUDGET_VERSION_ID BUDGET_VERSION_ID, ENCUMBRANCE_TYPE_ID ENCUMBRANCE_TYPE_ID, TEMPLATE_ID TEMPLATE_ID, MAX_DELTA_RUN_ID MAX_DELTA_RUN_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_EXTRACT_HISTORY";


