CREATE OR REPLACE VIEW GL_FIXED_CONV_RATES# AS
select OLD_CURRENCY OLD_CURRENCY, REPLACEMENT_CURRENCY REPLACEMENT_CURRENCY, FIXED_CONVERSION_RATE FIXED_CONVERSION_RATE, EFFECTIVE_START_DATE EFFECTIVE_START_DATE, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_FIXED_CONV_RATES";


