CREATE OR REPLACE VIEW GL_IEA_RECUR_HISTORY# AS
select RECURRING_BATCH_ID RECURRING_BATCH_ID, TRANSACTION_RUN_ID TRANSACTION_RUN_ID, RUN_STATUS RUN_STATUS, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, REQUEST_ID REQUEST_ID, PROGRAM_APPLICATION_ID PROGRAM_APPLICATION_ID, PROGRAM_ID PROGRAM_ID, PROGRAM_UPDATE_DATE PROGRAM_UPDATE_DATE from "GL"."GL_IEA_RECUR_HISTORY";


