CREATE OR REPLACE VIEW GL_INTERFACE_CONTROL# AS
select JE_SOURCE_NAME JE_SOURCE_NAME, STATUS STATUS, INTERFACE_RUN_ID INTERFACE_RUN_ID, GROUP_ID GROUP_ID, SET_OF_BOOKS_ID SET_OF_BOOKS_ID, PACKET_ID PACKET_ID, INTERFACE_TABLE_NAME INTERFACE_TABLE_NAME, PROCESSED_TABLE_CODE PROCESSED_TABLE_CODE, REQUEST_ID REQUEST_ID from "GL"."GL_INTERFACE_CONTROL";


