CREATE OR REPLACE VIEW GL_IMP_COA_ERR_INTERFACE# AS
select ERR_MESSAGE_ID ERR_MESSAGE_ID, INT_TABLE_NAME INT_TABLE_NAME, INTERFACE_ID INTERFACE_ID, MESSAGE_NUM MESSAGE_NUM, MESSAGE_TEXT MESSAGE_TEXT, CREATED_BY CREATED_BY, CREATION_DATE CREATION_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, REQUEST_ID REQUEST_ID, PROGRAM_APPLICATION_ID PROGRAM_APPLICATION_ID, PROGRAM_ID PROGRAM_ID, PROGRAM_UPDATE_DATE PROGRAM_UPDATE_DATE from "GL"."GL_IMP_COA_ERR_INTERFACE";


