CREATE OR REPLACE VIEW GL_IMPORT_REFERENCES# AS
select JE_BATCH_ID JE_BATCH_ID, JE_HEADER_ID JE_HEADER_ID, JE_LINE_NUM JE_LINE_NUM, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, REFERENCE_1 REFERENCE_1, REFERENCE_2 REFERENCE_2, REFERENCE_3 REFERENCE_3, REFERENCE_4 REFERENCE_4, REFERENCE_5 REFERENCE_5, REFERENCE_6 REFERENCE_6, REFERENCE_7 REFERENCE_7, REFERENCE_8 REFERENCE_8, REFERENCE_9 REFERENCE_9, REFERENCE_10 REFERENCE_10, SUBLEDGER_DOC_SEQUENCE_ID SUBLEDGER_DOC_SEQUENCE_ID, SUBLEDGER_DOC_SEQUENCE_VALUE SUBLEDGER_DOC_SEQUENCE_VALUE, GL_SL_LINK_ID GL_SL_LINK_ID, GL_SL_LINK_TABLE GL_SL_LINK_TABLE from "GL"."GL_IMPORT_REFERENCES";


