CREATE OR REPLACE VIEW GL_ISPEED_COA_TEMPLATES# AS
select COA_TEMPLATE_ID COA_TEMPLATE_ID, COA_NAME COA_NAME, NUMBER_OF_SEGMENTS NUMBER_OF_SEGMENTS, DESCRIPTION DESCRIPTION, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_ISPEED_COA_TEMPLATES";


