CREATE OR REPLACE VIEW GL_JE_LINES_RECON# AS
select JE_HEADER_ID JE_HEADER_ID, JE_LINE_NUM JE_LINE_NUM, LEDGER_ID LEDGER_ID, CREATED_BY CREATED_BY, CREATION_DATE CREATION_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, JGZZ_RECON_STATUS JGZZ_RECON_STATUS, JGZZ_RECON_DATE JGZZ_RECON_DATE, JGZZ_RECON_ID JGZZ_RECON_ID, JGZZ_RECON_REF JGZZ_RECON_REF from "GL"."GL_JE_LINES_RECON";


