CREATE OR REPLACE VIEW GL_JE_CATEGORIES_TL# AS
select JE_CATEGORY_NAME JE_CATEGORY_NAME, USER_JE_CATEGORY_NAME USER_JE_CATEGORY_NAME, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, DESCRIPTION DESCRIPTION, ATTRIBUTE1 ATTRIBUTE1, ATTRIBUTE2 ATTRIBUTE2, ATTRIBUTE3 ATTRIBUTE3, ATTRIBUTE4 ATTRIBUTE4, ATTRIBUTE5 ATTRIBUTE5, CONTEXT CONTEXT, REVERSAL_OPTION_CODE REVERSAL_OPTION_CODE, LANGUAGE LANGUAGE, SOURCE_LANG SOURCE_LANG, CONSOLIDATION_FLAG CONSOLIDATION_FLAG, JE_CATEGORY_KEY JE_CATEGORY_KEY, ZD_EDITION_NAME ZD_EDITION_NAME from "GL"."GL_JE_CATEGORIES_TL";


