CREATE OR REPLACE VIEW GL_LEDGER_SEGMENT_VALUES# AS
select LEDGER_ID LEDGER_ID, SEGMENT_TYPE_CODE SEGMENT_TYPE_CODE, SEGMENT_VALUE SEGMENT_VALUE, PARENT_RECORD_ID PARENT_RECORD_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, END_DATE END_DATE, START_DATE START_DATE, STATUS_CODE STATUS_CODE, LEGAL_ENTITY_ID LEGAL_ENTITY_ID, SLA_SEQUENCING_FLAG SLA_SEQUENCING_FLAG from "GL"."GL_LEDGER_SEGMENT_VALUES";


