CREATE OR REPLACE VIEW GL_LE_VALUE_SETS# AS
select LEGAL_ENTITY_ID LEGAL_ENTITY_ID, FLEX_VALUE_SET_ID FLEX_VALUE_SET_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY from "GL"."GL_LE_VALUE_SETS";


