CREATE OR REPLACE VIEW GL_LEDGER_CONFIG_DETAILS# AS
select CONFIGURATION_ID CONFIGURATION_ID, OBJECT_TYPE_CODE OBJECT_TYPE_CODE, OBJECT_ID OBJECT_ID, OBJECT_NAME OBJECT_NAME, SETUP_STEP_CODE SETUP_STEP_CODE, NEXT_ACTION_CODE NEXT_ACTION_CODE, STATUS_CODE STATUS_CODE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE from "GL"."GL_LEDGER_CONFIG_DETAILS";


