CREATE OR REPLACE VIEW GL_LEDGER_SET_ASSIGNMENTS# AS
select LEDGER_SET_ID LEDGER_SET_ID, LEDGER_ID LEDGER_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, START_DATE START_DATE, END_DATE END_DATE, STATUS_CODE STATUS_CODE from "GL"."GL_LEDGER_SET_ASSIGNMENTS";


