CREATE OR REPLACE VIEW GL_LEGAL_ENTITIES_BSVS# AS
select LEGAL_ENTITY_ID LEGAL_ENTITY_ID, FLEX_VALUE_SET_ID FLEX_VALUE_SET_ID, FLEX_SEGMENT_VALUE FLEX_SEGMENT_VALUE, START_DATE START_DATE, END_DATE END_DATE, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY from "GL"."GL_LEGAL_ENTITIES_BSVS";


