CREATE OR REPLACE VIEW GL_LEDGER_SET_REQUESTS# AS
select PARENT_REQUEST_ID PARENT_REQUEST_ID, CHILD_REQUEST_ID CHILD_REQUEST_ID, STATUS_CODE STATUS_CODE, LEDGER_SET_ID LEDGER_SET_ID, LEDGER_ID LEDGER_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, ERROR_MESSAGE ERROR_MESSAGE from "GL"."GL_LEDGER_SET_REQUESTS";


