CREATE OR REPLACE VIEW GL_LOOKUPS_OLD# AS
select LOOKUP_TYPE LOOKUP_TYPE, LOOKUP_CODE LOOKUP_CODE, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, MEANING MEANING, DESCRIPTION DESCRIPTION, ENABLED_FLAG ENABLED_FLAG, START_DATE_ACTIVE START_DATE_ACTIVE, END_DATE_ACTIVE END_DATE_ACTIVE, CONTEXT CONTEXT, ATTRIBUTE1 ATTRIBUTE1, ATTRIBUTE2 ATTRIBUTE2, ATTRIBUTE3 ATTRIBUTE3, ATTRIBUTE4 ATTRIBUTE4, ATTRIBUTE5 ATTRIBUTE5, ATTRIBUTE6 ATTRIBUTE6, ATTRIBUTE7 ATTRIBUTE7, ATTRIBUTE8 ATTRIBUTE8, ATTRIBUTE9 ATTRIBUTE9, ATTRIBUTE10 ATTRIBUTE10, ATTRIBUTE11 ATTRIBUTE11, ATTRIBUTE12 ATTRIBUTE12, ATTRIBUTE13 ATTRIBUTE13, ATTRIBUTE14 ATTRIBUTE14, ATTRIBUTE15 ATTRIBUTE15 from "GL"."GL_LOOKUPS_OLD";


