CREATE OR REPLACE VIEW GL_MGT_SEG_UPGRADE_H# AS
select CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID, MGT_SEG_COLUMN_NAME MGT_SEG_COLUMN_NAME, ASSIGN_COMPLETE_FLAG ASSIGN_COMPLETE_FLAG, MAX_PROCESSED_BATCH_ID MAX_PROCESSED_BATCH_ID, MAX_BATCH_ID MAX_BATCH_ID, CREATED_BY CREATED_BY, CREATION_DATE CREATION_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_MGT_SEG_UPGRADE_H";


