CREATE OR REPLACE VIEW GL_MGT_SEG_UPGRADE# AS
select CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID, JE_BATCH_ID JE_BATCH_ID, CREATED_BY CREATED_BY, CREATION_DATE CREATION_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_MGT_SEG_UPGRADE";


