CREATE OR REPLACE VIEW GL_MC_UPGRADE_RATES# AS
select UPGRADE_RUN_ID UPGRADE_RUN_ID, FROM_CURRENCY FROM_CURRENCY, TO_CURRENCY TO_CURRENCY, DENOMINATOR_RATE DENOMINATOR_RATE, NUMERATOR_RATE NUMERATOR_RATE, CONVERSION_RATE CONVERSION_RATE, PRECISION PRECISION, MINIMUM_ACCOUNTABLE_UNIT MINIMUM_ACCOUNTABLE_UNIT from "GL"."GL_MC_UPGRADE_RATES";


