CREATE OR REPLACE VIEW GL_NET_INCOME_ACCOUNTS# AS
select LEDGER_ID LEDGER_ID, BAL_SEG_VALUE BAL_SEG_VALUE, CODE_COMBINATION_ID CODE_COMBINATION_ID, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, REQUEST_ID REQUEST_ID, PROGRAM_APPLICATION_ID PROGRAM_APPLICATION_ID, PROGRAM_ID PROGRAM_ID, PROGRAM_UPDATE_DATE PROGRAM_UPDATE_DATE from "GL"."GL_NET_INCOME_ACCOUNTS";


