CREATE OR REPLACE VIEW GL_OASIS_SUMMARY_DATA# AS
select SET_OF_BOOKS_ID SET_OF_BOOKS_ID, FIN_ITEM_ID FIN_ITEM_ID, DRILLDOWN_SEGNUM1 DRILLDOWN_SEGNUM1, DRILLDOWN_SEGNUM2 DRILLDOWN_SEGNUM2, ACTUAL_FLAG ACTUAL_FLAG, DRILLDOWN_SEGVAL1 DRILLDOWN_SEGVAL1, DRILLDOWN_SEGVAL2 DRILLDOWN_SEGVAL2, RELATIVE_PERIOD_POS RELATIVE_PERIOD_POS, PERIOD_NAME PERIOD_NAME, PERIOD_YEAR PERIOD_YEAR, PERIOD_NUM PERIOD_NUM, PERIOD_TO_DATE PERIOD_TO_DATE, QUARTER_TO_DATE QUARTER_TO_DATE, YEAR_TO_DATE YEAR_TO_DATE, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, QUARTER_NUM QUARTER_NUM, DRILLDOWN_SEGDESC1 DRILLDOWN_SEGDESC1, DRILLDOWN_SEGDESC2 DRILLDOWN_SEGDESC2 from "GL"."GL_OASIS_SUMMARY_DATA";


