CREATE OR REPLACE VIEW GL_OASIS_FIN_METRICS_11I# AS
select SET_OF_BOOKS_ID SET_OF_BOOKS_ID, FIN_METRIC_CODE FIN_METRIC_CODE, EFFECTIVE_PERIOD_NUM EFFECTIVE_PERIOD_NUM, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, REPORT_NAME REPORT_NAME, REPORT_PARAMETERS REPORT_PARAMETERS, QUARTER1_VALUE QUARTER1_VALUE, QUARTER2_VALUE QUARTER2_VALUE, QUARTER3_VALUE QUARTER3_VALUE, QUARTER4_VALUE QUARTER4_VALUE, YEAR_VALUE YEAR_VALUE from "GL"."GL_OASIS_FIN_METRICS_11I";


