CREATE OR REPLACE VIEW GL_PERIOD_SETS# AS
select PERIOD_SET_NAME PERIOD_SET_NAME, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, DESCRIPTION DESCRIPTION, ATTRIBUTE1 ATTRIBUTE1, ATTRIBUTE2 ATTRIBUTE2, ATTRIBUTE3 ATTRIBUTE3, ATTRIBUTE4 ATTRIBUTE4, ATTRIBUTE5 ATTRIBUTE5, CONTEXT CONTEXT, PERIOD_SET_ID PERIOD_SET_ID, SECURITY_FLAG SECURITY_FLAG, ZD_EDITION_NAME ZD_EDITION_NAME from "GL"."GL_PERIOD_SETS";


