CREATE OR REPLACE VIEW GL_REVALUATION_11I# AS
select CODE_COMBINATION_ID CODE_COMBINATION_ID, SET_OF_BOOKS_ID SET_OF_BOOKS_ID, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_REVALUATION_11I";


