CREATE OR REPLACE VIEW GL_RECURRING_LINES# AS
select RECURRING_HEADER_ID RECURRING_HEADER_ID, RECURRING_LINE_NUM RECURRING_LINE_NUM, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CODE_COMBINATION_ID CODE_COMBINATION_ID, ENTERED_CURRENCY_CODE ENTERED_CURRENCY_CODE, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, DESCRIPTION DESCRIPTION, ENTERED_DR ENTERED_DR, ENTERED_CR ENTERED_CR, ATTRIBUTE1 ATTRIBUTE1, ATTRIBUTE2 ATTRIBUTE2, ATTRIBUTE3 ATTRIBUTE3, ATTRIBUTE4 ATTRIBUTE4, ATTRIBUTE5 ATTRIBUTE5, ATTRIBUTE6 ATTRIBUTE6, ATTRIBUTE7 ATTRIBUTE7, ATTRIBUTE8 ATTRIBUTE8, ATTRIBUTE9 ATTRIBUTE9, ATTRIBUTE10 ATTRIBUTE10, CONTEXT CONTEXT from "GL"."GL_RECURRING_LINES";


