CREATE OR REPLACE VIEW GL_ROW_MULTIPLIERS# AS
select MULTIPLIER MULTIPLIER, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_ROW_MULTIPLIERS";


