CREATE OR REPLACE VIEW GL_SEGMENT_FREQUENCIES# AS
select STRUCTURE_ID STRUCTURE_ID, SEGMENT_NAME SEGMENT_NAME, SEGMENT_VALUE SEGMENT_VALUE, ROWS_THIS_VALUE ROWS_THIS_VALUE from "GL"."GL_SEGMENT_FREQUENCIES";


