CREATE OR REPLACE VIEW GL_SEGVAL_INHERIT_HISTORY# AS
select CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID, LAST_RUN_DATE LAST_RUN_DATE, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, REQUEST_ID REQUEST_ID, PROGRAM_APPLICATION_ID PROGRAM_APPLICATION_ID, PROGRAM_ID PROGRAM_ID, PROGRAM_UPDATE_DATE PROGRAM_UPDATE_DATE from "GL"."GL_SEGVAL_INHERIT_HISTORY";


