CREATE OR REPLACE VIEW GL_SYSTEM_USAGES# AS
select AVERAGE_BALANCES_FLAG AVERAGE_BALANCES_FLAG, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CONSOLIDATION_LEDGER_FLAG CONSOLIDATION_LEDGER_FLAG, EFB_UPGRADE_FLAG EFB_UPGRADE_FLAG, RECONCILIATION_UPG_FLAG RECONCILIATION_UPG_FLAG from "GL"."GL_SYSTEM_USAGES";


