CREATE OR REPLACE VIEW GL_SEG_VAL_HIERARCHIES# AS
select FLEX_VALUE_SET_ID FLEX_VALUE_SET_ID, PARENT_FLEX_VALUE PARENT_FLEX_VALUE, CHILD_FLEX_VALUE CHILD_FLEX_VALUE, SUMMARY_FLAG SUMMARY_FLAG, CREATED_BY CREATED_BY, CREATION_DATE CREATION_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, STATUS_CODE STATUS_CODE from "GL"."GL_SEG_VAL_HIERARCHIES";


