CREATE OR REPLACE VIEW GL_SUMMARY_BC_OPTIONS# AS
select TEMPLATE_ID TEMPLATE_ID, FUNDING_BUDGET_VERSION_ID FUNDING_BUDGET_VERSION_ID, FUNDS_CHECK_LEVEL_CODE FUNDS_CHECK_LEVEL_CODE, DR_CR_CODE DR_CR_CODE, AMOUNT_TYPE AMOUNT_TYPE, BOUNDARY_CODE BOUNDARY_CODE, CREATED_BY CREATED_BY, CREATION_DATE CREATION_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, LAST_UPDATE_DATE LAST_UPDATE_DATE from "GL"."GL_SUMMARY_BC_OPTIONS";


