CREATE OR REPLACE VIEW GL_STORAGE_PARAMETERS# AS
select OBJECT_NAME OBJECT_NAME, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, OBJECT_TYPE OBJECT_TYPE, TABLESPACE_NAME TABLESPACE_NAME, INITIAL_EXTENT_SIZE_KB INITIAL_EXTENT_SIZE_KB, NEXT_EXTENT_SIZE_KB NEXT_EXTENT_SIZE_KB, MAX_EXTENTS MAX_EXTENTS, PCT_INCREASE PCT_INCREASE, DESCRIPTION DESCRIPTION, PCT_FREE PCT_FREE, ZD_EDITION_NAME ZD_EDITION_NAME from "GL"."GL_STORAGE_PARAMETERS";


