CREATE OR REPLACE VIEW GL_SYSTEM_SETUP_11I# AS
select SET_OF_BOOKS_ID SET_OF_BOOKS_ID, INDEXED_SEGMENT INDEXED_SEGMENT, RECORDS_TO_PROCESS RECORDS_TO_PROCESS, FLEX_CACHE_SIZE FLEX_CACHE_SIZE, ARCHIVE_EASYLINK_FLAG ARCHIVE_EASYLINK_FLAG, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, ROLLBACK_SEGMENT ROLLBACK_SEGMENT from "GL"."GL_SYSTEM_SETUP_11I";


