CREATE OR REPLACE VIEW GL_TRACK_DELTA_BALANCES# AS
select LEDGER_ID LEDGER_ID, PROGRAM_CODE PROGRAM_CODE, PERIOD_NAME PERIOD_NAME, ACTUAL_FLAG ACTUAL_FLAG, EXTRACT_LEVEL_CODE EXTRACT_LEVEL_CODE, CURRENCY_TYPE_CODE CURRENCY_TYPE_CODE, ENABLED_FLAG ENABLED_FLAG, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_TRACK_DELTA_BALANCES";


