CREATE OR REPLACE VIEW GL_XFR_LEDGER_BSV_MAPS# AS
select SYSTEM_MAP_ID SYSTEM_MAP_ID, LEDGER_ID LEDGER_ID, BALANCING_SEGMENT_VALUE BALANCING_SEGMENT_VALUE, OBJECT_VERSION_NUMBER OBJECT_VERSION_NUMBER, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, LEDGER_BSV_MAP_ID LEDGER_BSV_MAP_ID from "GL"."GL_XFR_LEDGER_BSV_MAPS";


