CREATE OR REPLACE VIEW GL_XFR_PERIOD_MAPPINGS# AS
select CALENDAR_MAPPING_ID CALENDAR_MAPPING_ID, FROM_PERIOD_NAME FROM_PERIOD_NAME, FROM_EFF_PER_NUM FROM_EFF_PER_NUM, TO_PERIOD_NAME TO_PERIOD_NAME, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_XFR_PERIOD_MAPPINGS";


