CREATE OR REPLACE VIEW GL_XFR_SYSTEM_LEDGERS# AS
select SYSTEM_MAP_ID SYSTEM_MAP_ID, LEDGER_ID LEDGER_ID, BSV_ASSIGNMENT_TYPE BSV_ASSIGNMENT_TYPE, OBJECT_VERSION_NUMBER OBJECT_VERSION_NUMBER, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, SYSTEM_LEDGER_MAP_ID SYSTEM_LEDGER_MAP_ID from "GL"."GL_XFR_SYSTEM_LEDGERS";


