CREATE OR REPLACE VIEW GL_XFR_SOURCE_SYSTEMS# AS
select SYSTEM_MAP_ID SYSTEM_MAP_ID, SYSTEM_ID SYSTEM_ID, NAME NAME, JE_SOURCE_KEY JE_SOURCE_KEY, DESCRIPTION DESCRIPTION, DRILLDOWN_URL DRILLDOWN_URL, OBJECT_VERSION_NUMBER OBJECT_VERSION_NUMBER, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_XFR_SOURCE_SYSTEMS";


