CREATE OR REPLACE VIEW GL_XFR_CCID_MAPPINGS# AS
select LEDGER_MAPPING_ID LEDGER_MAPPING_ID, FROM_CCID FROM_CCID, TO_CCID TO_CCID, PERIOD_NAME PERIOD_NAME, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_XFR_CCID_MAPPINGS";


