CREATE OR REPLACE VIEW GL_XFR_LEDGER_MAPPINGS# AS
select LEDGER_MAPPING_ID LEDGER_MAPPING_ID, FROM_LEDGER_ID FROM_LEDGER_ID, FROM_LEDGER_CURRENCY FROM_LEDGER_CURRENCY, TO_LEDGER_ID TO_LEDGER_ID, COA_MAPPING_ID COA_MAPPING_ID, CALENDAR_MAPPING_ID CALENDAR_MAPPING_ID, MAX_DELTA_RUN_ID MAX_DELTA_RUN_ID, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, FIRST_EFF_PER_NUM FIRST_EFF_PER_NUM from "GL"."GL_XFR_LEDGER_MAPPINGS";


