CREATE OR REPLACE VIEW GL_XFR_LED_MAP_PERIODS# AS
select LEDGER_MAPPING_ID LEDGER_MAPPING_ID, FROM_PERIOD_NAME FROM_PERIOD_NAME, FROM_EFF_PER_NUM FROM_EFF_PER_NUM, FULL_TRANSFER_DONE_FLAG FULL_TRANSFER_DONE_FLAG, MAX_DELTA_RUN_ID MAX_DELTA_RUN_ID, TEMP_DATE TEMP_DATE, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN from "GL"."GL_XFR_LED_MAP_PERIODS";


