CREATE OR REPLACE VIEW GL_YEAR_END_BAL_INT_1# AS
select CODE_COMBINATION_ID CODE_COMBINATION_ID, CURRENCY_CODE CURRENCY_CODE, BALANCING_SEGMENT BALANCING_SEGMENT, CLOSING_ACCOUNT CLOSING_ACCOUNT, YEAR_TO_DATE_DR YEAR_TO_DATE_DR, YEAR_TO_DATE_CR YEAR_TO_DATE_CR, YEAR_TO_DATE_DR_BEQ YEAR_TO_DATE_DR_BEQ, YEAR_TO_DATE_CR_BEQ YEAR_TO_DATE_CR_BEQ, TRANSLATED_FLAG TRANSLATED_FLAG from "GL"."GL_YEAR_END_BAL_INT_1";


