CREATE OR REPLACE VIEW JE_BE_VAT_REP_RULES# AS
select SOURCE SOURCE, OF_TRANS_TYPE OF_TRANS_TYPE, VAT_TRANS_TYPE VAT_TRANS_TYPE, LINE_TYPE LINE_TYPE, TAX_NAME TAX_NAME, VAT_REPORT_BOX VAT_REPORT_BOX, SIGN_FLAG SIGN_FLAG, START_DATE_ACTIVE START_DATE_ACTIVE, END_DATE_ACTIVE END_DATE_ACTIVE, ENABLED_FLAG ENABLED_FLAG, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, SET_OF_BOOKS_ID SET_OF_BOOKS_ID, NOREC_VAT_REP_BOX NOREC_VAT_REP_BOX from "GL"."JE_BE_VAT_REP_RULES";


