CREATE OR REPLACE VIEW JE_BE_ANNUAL_VAT# AS
select COLUMN1 COLUMN1, COLUMN2 COLUMN2, COLUMN3 COLUMN3, COLUMN4 COLUMN4, COLUMN5 COLUMN5, COLUMN6 COLUMN6, COLUMN7 COLUMN7, COLUMN8 COLUMN8, COLUMN9 COLUMN9, COLUMN10 COLUMN10, CUSTOMER_ID CUSTOMER_ID, SET_OF_BOOKS_ID SET_OF_BOOKS_ID from "GL"."JE_BE_ANNUAL_VAT";


