CREATE OR REPLACE VIEW JE_BE_VAT_ALLOC_ERRORS# AS
select SOURCE SOURCE, SET_OF_BOOKS_ID SET_OF_BOOKS_ID, TRANS_ID TRANS_ID, TRANS_LINE_ID TRANS_LINE_ID, OF_TRANS_TYPE OF_TRANS_TYPE, VAT_TRANS_TYPE VAT_TRANS_TYPE, LINE_TYPE LINE_TYPE, TAX_NAME TAX_NAME, AMOUNT AMOUNT, TRANS_DATE TRANS_DATE, ERROR_NUMBER ERROR_NUMBER, ERROR_DESCRIPTION ERROR_DESCRIPTION, POSTED_FLAG POSTED_FLAG, PERIOD_NAME PERIOD_NAME from "GL"."JE_BE_VAT_ALLOC_ERRORS";


