CREATE OR REPLACE VIEW JE_GR_JE_HEADER_SEQUENCE# AS
select JE_HEADER_ID JE_HEADER_ID, DOC_SEQUENCE_ID DOC_SEQUENCE_ID, DOC_SEQUENCE_VALUE DOC_SEQUENCE_VALUE, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY from "GL"."JE_GR_JE_HEADER_SEQUENCE";


