CREATE OR REPLACE VIEW JE_IT_REPORT_PARAMETERS# AS
select CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CONCURRENT_PROGRAM_ID CONCURRENT_PROGRAM_ID, SET_OF_BOOKS_ID SET_OF_BOOKS_ID, REQUEST_ID REQUEST_ID, RUN_DATE RUN_DATE, PARAMETER_1 PARAMETER_1, PARAMETER_2 PARAMETER_2, PARAMETER_3 PARAMETER_3, PARAMETER_4 PARAMETER_4, PARAMETER_5 PARAMETER_5, REPORT_STATUS REPORT_STATUS from "GL"."JE_IT_REPORT_PARAMETERS";


