CREATE OR REPLACE VIEW JG_ZZ_TA_ALLOCATED_LINES# AS
select JE_BATCH_ID JE_BATCH_ID, REQUEST_ID REQUEST_ID, JE_HEADER_ID JE_HEADER_ID, JE_LINE_NUM JE_LINE_NUM, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, PROGRAM_APPLICATION_ID PROGRAM_APPLICATION_ID, PROGRAM_ID PROGRAM_ID, PROGRAM_UPDATE_DATE PROGRAM_UPDATE_DATE from "GL"."JG_ZZ_TA_ALLOCATED_LINES";


