CREATE OR REPLACE VIEW JG_ZZ_TA_RULE_LINES# AS
select ACCOUNT_RANGE_ID ACCOUNT_RANGE_ID, RULE_LINE_ID RULE_LINE_ID, NATURAL_ACCOUNT NATURAL_ACCOUNT, ALLOCATION_PERCENT ALLOCATION_PERCENT, CREATION_DATE CREATION_DATE, CREATED_BY CREATED_BY, LAST_UPDATED_BY LAST_UPDATED_BY, LAST_UPDATE_DATE LAST_UPDATE_DATE, OFFSET_ACCOUNT OFFSET_ACCOUNT, LAST_UPDATE_LOGIN LAST_UPDATE_LOGIN, CONTEXT CONTEXT, ATTRIBUTE1 ATTRIBUTE1, ATTRIBUTE2 ATTRIBUTE2, ATTRIBUTE3 ATTRIBUTE3, ATTRIBUTE4 ATTRIBUTE4, ATTRIBUTE5 ATTRIBUTE5, ATTRIBUTE6 ATTRIBUTE6, ATTRIBUTE7 ATTRIBUTE7, ATTRIBUTE8 ATTRIBUTE8, ATTRIBUTE9 ATTRIBUTE9, ATTRIBUTE10 ATTRIBUTE10, ATTRIBUTE11 ATTRIBUTE11, ATTRIBUTE12 ATTRIBUTE12, ATTRIBUTE13 ATTRIBUTE13, ATTRIBUTE14 ATTRIBUTE14, ATTRIBUTE15 ATTRIBUTE15 from "GL"."JG_ZZ_TA_RULE_LINES";


