CREATE TABLE fnd_flex_values_tl (
	 flex_value_id NUMBER(15,0) NOT NULL
	,language VARCHAR2 (30) NOT NULL
	,last_update_date DATE NOT NULL
	,last_updated_by NUMBER(15,0) NOT NULL
	,creation_date DATE NOT NULL
	,created_by NUMBER(15,0) NOT NULL
	,last_update_login NUMBER(10,0)
	,description VARCHAR2 (240)
	,source_lang VARCHAR2 (4) NOT NULL
	,flex_value_meaning VARCHAR2 (150) NOT NULL
	,security_group_id NUMBER
	,zd_edition_name VARCHAR2 (30) DEFAULT 'ORA$BASE' NOT NULL
	,zd_sync VARCHAR2 (30) DEFAULT 'SYNCED' NOT NULL
);

CREATE  INDEX FND_FLEX_VALUES_TL_F1 ON FND_FLEX_VALUES_TL (UPPER("DESCRIPTION"));
CREATE  INDEX FND_FLEX_VALUES_TL_N1 ON FND_FLEX_VALUES_TL (DESCRIPTION, LANGUAGE);
CREATE  INDEX FND_FLEX_VALUES_TL_N2 ON FND_FLEX_VALUES_TL (FLEX_VALUE_MEANING, LANGUAGE);
CREATE UNIQUE INDEX FND_FLEX_VALUES_TL_U1 ON FND_FLEX_VALUES_TL (FLEX_VALUE_ID, LANGUAGE, ZD_EDITION_NAME);
