CREATE TABLE gl_account_hierarchies (
	 ledger_id NUMBER(15,0) NOT NULL
	,summary_code_combination_id NUMBER(15,0) NOT NULL
	,detail_code_combination_id NUMBER(15,0) NOT NULL
	,template_id NUMBER(15,0) NOT NULL
	,last_updated_by NUMBER(15,0) NOT NULL
	,last_update_date DATE NOT NULL
	,ordering_value VARCHAR2 (25) NOT NULL
);

CREATE  INDEX GL_ACCOUNT_HIERARCHIES_N1 ON GL_ACCOUNT_HIERARCHIES (DETAIL_CODE_COMBINATION_ID);
CREATE UNIQUE INDEX GL_ACCOUNT_HIERARCHIES_U1 ON GL_ACCOUNT_HIERARCHIES (SUMMARY_CODE_COMBINATION_ID, DETAIL_CODE_COMBINATION_ID);
CREATE UNIQUE INDEX GL_ACCOUNT_HIERARCHIES_U2 ON GL_ACCOUNT_HIERARCHIES (LEDGER_ID, DETAIL_CODE_COMBINATION_ID, TEMPLATE_ID, SUMMARY_CODE_COMBINATION_ID);
